# Generated by Django 4.1.1 on 2022-09-16 14:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('JSGame_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Game',
            new_name='Save',
        ),
        migrations.AlterField(
            model_name='asset',
            name='file',
            field=models.ImageField(null=True, upload_to='assets'),
        ),
    ]
