# Generated by Django 4.1.1 on 2022-09-16 15:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('JSGame_api', '0002_rename_game_save_alter_asset_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('access_code', models.CharField(max_length=7)),
                ('background_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='background_asset', to='JSGame_api.asset')),
                ('character_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character_asset', to='JSGame_api.asset')),
                ('collectable_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collectable_asset', to='JSGame_api.asset')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('enemy_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enemy_asset', to='JSGame_api.asset')),
                ('trophy_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trophy_asset', to='JSGame_api.asset')),
            ],
        ),
    ]
