# Generated by Django 4.1.1 on 2022-09-16 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JSGame_api', '0003_game'),
    ]

    operations = [
        migrations.RenameField(
            model_name='save',
            old_name='user',
            new_name='player',
        ),
    ]
