# Generated by Django 4.1.1 on 2022-09-16 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('JSGame_api', '0004_rename_user_save_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='other_asset',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='other_asset', to='JSGame_api.asset'),
            preserve_default=False,
        ),
    ]
