# Generated by Django 4.1.1 on 2022-09-19 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('JSGame_api', '0005_game_other_asset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='access_code',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='background_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='background_asset', to='JSGame_api.asset'),
        ),
        migrations.AlterField(
            model_name='game',
            name='character_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='character_asset', to='JSGame_api.asset'),
        ),
        migrations.AlterField(
            model_name='game',
            name='collectable_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collectable_asset', to='JSGame_api.asset'),
        ),
        migrations.AlterField(
            model_name='game',
            name='enemy_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enemy_asset', to='JSGame_api.asset'),
        ),
        migrations.AlterField(
            model_name='game',
            name='other_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='other_asset', to='JSGame_api.asset'),
        ),
        migrations.AlterField(
            model_name='game',
            name='trophy_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trophy_asset', to='JSGame_api.asset'),
        ),
    ]
