# Generated by Django 4.1.1 on 2022-09-20 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JSGame_api', '0006_alter_game_access_code_alter_game_background_asset_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trophy',
            name='awarded_trophies',
        ),
        migrations.AddField(
            model_name='save',
            name='awarded_trophies',
            field=models.ManyToManyField(blank=True, related_name='awarded_trophies', to='JSGame_api.trophy'),
        ),
    ]
