# Generated by Django 4.1.1 on 2022-09-27 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JSGame_api', '0007_remove_trophy_awarded_trophies_save_awarded_trophies'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='Frames',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
